Modul5
Maciej-Rzemek/AkademiaAndroida pull request #5
Opened 2021-01-06 21:30 UTC by Maciej-Rzemek

2021-01-11 08:01 UTC, keresmi requested changes
Dobrze by było stworzyć oddzielne modele dla warstwy prezentacji i domeny dla klas `Origin` i `Location`. Wtedy te poszczególne warstwy nie będą od siebie zależne. Reszta wydaje się być w porządku.

2021-01-11 08:01 UTC, patrykserek commented on app/src/main/java/com/example/akademiaandroida/features/data/remote/model/CharacterRemote.kt
> +data class Origin(
Ta klasa powinna mieć również końcówkę `Remote`, bo należy do warstwy danych.

2021-01-11 08:01 UTC, patrykserek commented on app/src/main/java/com/example/akademiaandroida/features/data/remote/model/CharacterRemote.kt
> +data class Location(
Ta klasa powinna mieć również końcówkę `Remote`, bo należy do warstwy danych.

2021-01-11 08:01 UTC, patrykserek commented on app/src/main/java/com/example/akademiaandroida/features/character/domain/model/Character.kt
> +    val origin: Origin,
Modele `Origin` i `Location` powinny mieć swoje odpowiedniki z warstwie domeny i w warstwie prezentacji. Aktualnie używany jest wszędzie ten sam model z warstwy danych.

2021-01-11 08:01 UTC, patrykserek commented on app/src/main/java/com/example/akademiaandroida/features/character/presentation/model/CharacterDisplayable.kt
> +    val origin: Origin,
Modele `Origin` i `Location` powinny mieć swoje odpowiedniki z warstwie domeny i w warstwie prezentacji. Aktualnie używany jest wszędzie ten sam model z warstwy danych.

2021-01-11 08:01 UTC, patrykserek commented on app/src/main/java/com/example/akademiaandroida/features/episodes/presentation/model/EpisodeDisplayable.kt
> +data class Episode(
Można tutaj zaznaczyć, że jest to klasa `EpisodeDisplayable`. Wtedy są mniejsze szanse o pomyłkę (ta sama nazwa nie występuję dwa razy).

2021-01-11 08:01 UTC, keresmi commented on app/src/main/java/com/example/akademiaandroida/features/location/presentation/model/LocationDisplayable.kt
> +data class Location(
Można tutaj zaznaczyć, że jest to klasa `LocationDisplayable`. Wtedy są mniejsze szanse o pomyłkę (ta sama nazwa nie występuję dwa razy).

2021-01-17 11:19 UTC, Maciej-Rzemek commented on app/src/main/java/com/example/akademiaandroida/features/data/remote/model/CharacterRemote.kt
> +data class Location(
klasę Origin i Location zrefactorowałem odpowiednio na CharacterOriginRemote, oraz CharacterLocationRemote, gdyż w pakiecie com.example.akademiaandroida.features.data.remote.model istnieje już LocationRemote i powstawał konflikt nazw. Nie jestem pewien czy konwencja nazewnictwa jest zachowana, choć mi wydaje się to całkiem sensowna :)

2021-01-17 13:06 UTC, closed without merging